services:
  db:
    image: postgres:17-alpine
    container_name: trans_solutions_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: TransSolutionsDB
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d TransSolutionsDB"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: TransSolutions.Api/Dockerfile
    image: trans-solutions-api:latest
    container_name: trans_solutions_api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=TransSolutionsDB;Username=admin;Password=password123
      - Jwt__Key=aec133a572f9082ad64bbb9a0bd73e74883136f4eacee318f4734f3285bf43d3
      - Jwt__Issuer=https://trans-solutions.com
      - Jwt__Audience=https://trans-solutions.com

volumes:
  postgres_data:
